### ISSUE TITLE
Warning when scanning containers

### ISSUE THREAD

**Issue by Namyalg** [Azure/container-scan#135] opened 2022-02-15 03:56 UTC
A scan on containers, is returning such a warning. 

Warning: An error occurred while creating the check run for container scan. Error: Error: An error occurred while creating scan result. Statuscode: 403, StatusMessage: Forbidden, head_sha: (sha mentioned)

**Comment by koushdey** [comment] 2022-02-22 10:45
@Namyalg Are you still facing the issue? Can you share logs or run URL? It would be better if you can run the workflow in debug mode to get detailed logs.

**Comment by Namyalg** [comment] 2022-02-25 13:03
![image](https://user-images.githubusercontent.com/53875297/155719572-c3467e6b-b6f8-4151-9f39-4fdec0856ac8.png)

This is the snapshot of the complete error, this is the run URL : https://github.com/moja-global/FLINT.Reporting/runs/5318206799?check_suite_focus=true

**Comment by hhwagner** [comment] 2022-02-27 14:30
#71 ? got the same error

**Comment by Namyalg** [comment] 2022-02-27 14:54
Yes, its the same

**Comment by koushdey** [comment] 2022-02-28 08:00
@Namyalg Can you check if Scanitizer app is installed on your repo or not?

**Comment by Namyalg** [comment] 2022-02-28 08:10
I installed it in the repository which is running the action, I still get the same error

**Comment by koushdey** [comment] 2022-04-11 10:40
@Namyalg I checked the [latest runs](https://github.com/moja-global/FLINT.Reporting/actions/runs/2145538260) and I see no container scan errors. I feel it was intermittent issue. Closing it as the issue is mitigated.

**Closed** 2022-04-11 10:40 UTC
Labels: idle, waiting-for-customer
